In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../datasets/surveys.csv')
df.head()

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        35549 non-null  int64
 1   month            35549 non-null  int64
 2   day              35549 non-null  int64
 3   year             35549 non-null  int64
 4   plot_id          35549 non-null  int64
 5   species_id       34786 non-null  object
 6   sex              33038 non-null  object
 7   hindfoot_length  31438 non-null  float64
 8   weight           32283 non-null  float64
dtypes: float64(2), int64(5), object(2)
memory usage: 2.4+ MB

In [7]:
df_2 = df.dropna(how='any')
df_2.head()

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
62,63,8,19,1977,3,DM,M,35.0,40.0
63,64,8,19,1977,7,DM,M,37.0,48.0
64,65,8,19,1977,4,DM,F,34.0,29.0
65,66,8,19,1977,4,DM,F,35.0,46.0
66,67,8,19,1977,7,DM,M,35.0,36.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        35549 non-null  int64
 1   month            35549 non-null  int64
 2   day              35549 non-null  int64
 3   year             35549 non-null  int64
 4   plot_id          35549 non-null  int64
 5   species_id       34786 non-null  object
 6   sex              33038 non-null  object
 7   hindfoot_length  31438 non-null  float64
 8   weight           32283 non-null  float64
dtypes: float64(2), int64(5), object(2)
memory usage: 2.4+ MB

In [11]:
filling_values = {"weight" : 0, "hindfoot_length": df['hindfoot_length'].mean(), "sex" : df['sex'].mode().iloc[0], "species_id" : df['species_id'].mode().iloc[0]}
df_5 = df.fillna(value= filling_values)
df_5

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.000000,0.0
1,2,7,16,1977,3,NL,M,33.000000,0.0
2,3,7,16,1977,2,DM,F,37.000000,0.0
3,4,7,16,1977,7,DM,M,36.000000,0.0
4,5,7,16,1977,3,DM,M,35.000000,0.0
...,...,...,...,...,...,...,...,...,...
35544,35545,12,31,2002,15,AH,M,29.287932,0.0
35545,35546,12,31,2002,15,AH,M,29.287932,0.0
35546,35547,12,31,2002,10,RM,F,15.000000,14.0
35547,35548,12,31,2002,7,DO,M,36.000000,51.0
35548,35549,12,31,2002,5,DM,M,29.287932,0.0

In [15]:
df = df.drop_duplicates()