### Series
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers,
Python objects, etc.). The axis labels are collectively referred to as the index.

In [11]:
import pandas as pd
import numpy as np

##### Create series from NumPy array
number of labels in 'index' must be the same as the number of elements in array

In [12]:
my_simple_series = pd.Series(np.random.randn(5), index=['a', 'b', 'c','d','e'])
my_simple_series

a   -0.466821
b    0.654524
c   -0.138025
d    1.590148
e    0.205290
dtype: float64

In [13]:

my_simple_series.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [14]:

my_simple_series.values

array([-0.46682146,  0.65452409, -0.13802524,  1.5901481 ,  0.20529017])

##### Create series from NumPy array, without explicit index

In [15]:
my_simple_series = pd.Series(np.random.randn(5))
my_simple_series

0    0.653009
1   -0.342987
2   -1.230140
3    2.131681
4   -1.080059
dtype: float64

Access a series like a NumPy array

In [16]:
my_simple_series[:3]

0    0.653009
1   -0.342987
2   -1.230140
dtype: float64



##### Create series from Python dictionary

In [17]:

my_dictionary = {'a' : 45., 'b' : -19.5, 'c' : 4444}
my_second_series = pd.Series(my_dictionary)
my_second_series

a      45.0
b     -19.5
c    4444.0
dtype: float64

Access a series like a dictionary

In [18]:
my_second_series['b']

-19.5

In [19]:
# if the value of E exsists the new one will be overridden 
# if not it will be created
pd.Series(my_dictionary, index=['b', 'c', 'd', 'a'])

b     -19.5
c    4444.0
d       NaN
a      45.0
dtype: float64

In [20]:
my_second_series.get('a')

45.0

In [21]:
unknown = my_second_series.get('f')
type(unknown)

NoneType

##### Create series from scalar
If data is a scalar value, an index must be provided. The value will be repeated to match the length of index

In [22]:
pd.Series(5., index=['a', 'b', 'c', 'd', 'e'])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

In [23]:
pd.Series(5.)

0    5.0
dtype: float64

### Time-series data

In [24]:

my_index = pd.date_range('13/1/2022', periods=9, freq='D')
my_series = pd.Series(np.arange(9), index=my_index) 
my_series

C:\Users\Eng Samy\AppData\Local\Temp\ipykernel_12132\3651291069.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  my_index = pd.date_range('13/1/2022', periods=9, freq='D')

2022-01-13    0
2022-01-14    1
2022-01-15    2
2022-01-16    3
2022-01-17    4
2022-01-18    5
2022-01-19    6
2022-01-20    7
2022-01-21    8
Freq: D, dtype: int32

In [25]:
my_index = pd.date_range('2022/01/13',periods= 9 , freq = 'D')
my_series = pd.Series(np.arange(9) , index=my_index)
my_series

2022-01-13    0
2022-01-14    1
2022-01-15    2
2022-01-16    3
2022-01-17    4
2022-01-18    5
2022-01-19    6
2022-01-20    7
2022-01-21    8
Freq: D, dtype: int32

In [26]:

my_series['2022-01-13 00:00:00' : '2022-01-13 00:06:00']

2022-01-13    0
Freq: D, dtype: int32

In [27]:
# you said from the day 13 : 16 and all the data locate in the day 13 so all the data will be shown
my_series['2022-01-13':'2022-01-16']

2022-01-13    0
2022-01-14    1
2022-01-15    2
2022-01-16    3
Freq: D, dtype: int32

- df.resample is a method in pandas that is used to resample time-series data in a DataFrame object. 
- Time-series data is data that is indexed by time, such as stock prices or weather data.

- The df.resample method groups the data in a DataFrame by a specified time interval and applies an   aggregation function, such as mean, sum, or count, to each group. 
- This can be used to perform operations such as downsampling (reducing the frequency of the data), upsampling (increasing the frequency of the data), and smoothing (reducing noise in the data).

- **The df.resample method requires a time-based index for the DataFrame, which can be created using the pd.to_datetime function or by setting the datetime column as the index using df.set_index('datetime').**

In [28]:
# The method takes a string argument that specifies the time interval for resampling, 
# such as 1D for daily or 1W for weekly, 
# or a Timedelta object that specifies the length of the resampling interval.
# df_weekly = df.resample('1W').mean()

my_series.resample('3min').sum()

2022-01-13 00:00:00    0
2022-01-13 00:03:00    0
2022-01-13 00:06:00    0
2022-01-13 00:09:00    0
2022-01-13 00:12:00    0
                      ..
2022-01-20 23:48:00    0
2022-01-20 23:51:00    0
2022-01-20 23:54:00    0
2022-01-20 23:57:00    0
2022-01-21 00:00:00    8
Freq: 3T, Length: 3841, dtype: int32

In [29]:
my_series.resample('3min', label='right').sum()

2022-01-13 00:03:00    0
2022-01-13 00:06:00    0
2022-01-13 00:09:00    0
2022-01-13 00:12:00    0
2022-01-13 00:15:00    0
                      ..
2022-01-20 23:51:00    0
2022-01-20 23:54:00    0
2022-01-20 23:57:00    0
2022-01-21 00:00:00    0
2022-01-21 00:03:00    8
Freq: 3T, Length: 3841, dtype: int32

### methods commonly used for analyzing and manipulating time series data.

 1. **pd.to_datetime()** : This method is used to convert date/time strings to pandas datetime objects, which can be used as an index for time series data.

In [30]:
# Create a DataFrame with a date column as a string
df = pd.DataFrame({'date': ['2022-01-01', '2022-01-02', '2022-01-03'], 'value': [10, 20, 30]})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      object
 1   value   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [33]:
# Convert the date column to a pandas datetime object to use it late


df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[ns]
 1   value   3 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 176.0 bytes

 2. **df.set_index()** : This method sets a specified column as the index of a DataFrame, which is useful when the DataFrame contains time series data.

In [38]:
# Create a DataFrame with a date column and a value column
df = pd.DataFrame({'date': ['2022-01-01', '2022-01-02', '2022-01-03'], 'value': [10, 20, 30]})
df

         date  value
0  2022-01-01     10
1  2022-01-02     20
2  2022-01-03     30

In [39]:
df.set_index('date',inplace=True)
df

            value
date
2022-01-01     10
2022-01-02     20
2022-01-03     30

3. **df.resample()**: This method is used to resample time series data to a lower or higher frequency, such as downsampling hourly data to daily data.

In [5]:
# Create a DataFrame with a daily datetime index and a value column
df = pd.DataFrame({'value': [10,20,30]} , index= pd.date_range(start='2022-01-01', end='2022-01-03', freq='D'))
df

            value
2022-01-01     10
2022-01-02     20
2022-01-03     30

In [8]:
# Resample the data to a weekly frequency and calculate the mean
# df_weekly = df.resample('W').mean()
# df_weekly

df_weekly = df.resample('W').mean()
df_weekly

            value
2022-01-02   15.0
2022-01-09   30.0

In [ ]:
# Sure! Based on the data you provided, the following is an explanation of the below results:

# value
# 2022-01-02	15.0
# This result is obtained by resampling the original data to a weekly frequency and taking the mean 
# of each week. Since there are two values in the first week (January 1st and January 2nd), 
# the mean of those two values is calculated, which is (10+20)/2 = 15.0. Therefore, 
# the value of 15.0 represents the average value of the first week of January 2022.

# value
# 2022-01-09	30.0
# This result is obtained by resampling the original data to a weekly frequency and taking the mean 
# of each week. Since there is only one value in the second week of January (January 3rd), 
# the mean of that value is simply the value itself, which is 30.0. Therefore, 
# the value of 30.0 represents the average value of the second week of January 2022.

In [ ]:
#                  sales
# 2019-01-01        10
# 2019-01-02        12
# 2019-01-03        8
# 2019-01-04        15
# 2019-01-07        18
# 2019-01-09        20
# 2019-01-10        14
# 2019-01-11        16
# 2019-01-14        12
# 2019-01-16        19

# After applying df.resample('W').mean(), the resulting df_weekly will be:

    
#                  sales
# 2018-12-30 to 2019-01-06     11.4
# 2019-01-06 to 2019-01-13     17.5
# 2019-01-13 to 2019-01-20     14.5


# For the first row:


# sales
# 2018-12-30 to 2019-01-06 = (10 + 12 + 8 + 15) / 4 = 11.4
# For the second row:

# sales
# 2019-01-06 to 2019-01-13 = (18 + 20 + 14 + 16) / 4 = 17.5
# For the third row:

# sales
# 2019-01-13 to 2019-01-20 = (12 + 19) / 2 = 14.5